" Define leader from the start
let mapleader = "\<Space>"

" ------ load plugins ------
if filereadable(expand("~/.vimrc.plugins"))
  source ~/.vimrc.plugins
endif

" ------ sensible defaults ------
set hlsearch
set incsearch
set number
set noswapfile
set hidden
set wrap!
set splitbelow splitright
set clipboard=unnamedplus
set visualbell
set mouse=a
set foldmethod=indent
set nofoldenable
" set lazyredraw
if has('mouse_sgr')
    set ttymouse=sgr
endif
set wildmode=longest,list,full
set noshowcmd noruler
set nomousehide

" disable F1
:nmap <F1> :echo<CR>
:imap <F1> <C-o>:echo<CR>

" fix tabs
set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4

" dont override files, just add new content
set backupcopy=yes

" copy wuihout
:map <leader>y "0y
:map <leader>p "0p

" ------ extra config ------
syntax on
filetype plugin indent on

" disable highlighting
set synmaxcol=120
syntax sync minlines=200

" move lines of code vertically
vnoremap < <gv
vnoremap > >gv

" navegate foward and backwards
map q :bp<cr>
map w :bn<cr>

" go to line
:nnoremap <CR> G

" Enable Ctrlc and CtrlV for vim (requires gvim)
vnoremap <C-c> "*y :let @+=@*<CR>
map <C-v> "+P

" splits
noremap <silent> <A-v> :vsplit<CR>
map <silent> <A-h> :split<CR>

" ctrl + s to save files
noremap <silent> <C-S> :update<CR>
vnoremap <silent> <C-S> <C-C>:update<CR>
inoremap <silent> <C-S> <C-O>:update<CR>

if !has('nvim')
  if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\e[5 q\<Esc>\\"
    let &t_SR = "\<Esc>Ptmux;\<Esc>\e[4 q\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\e[2 q\<Esc>\\"
  else
    let &t_SI = "\e[6 q"
    let &t_SR = "\e[4 q"
    let &t_EI = "\e[2 q"
  endif
endif

" trailing white space
autocmd BufWritePre * %s/\s\+$//e

 " when quitting a file, save the cursor position
augroup save_cursor_position
    autocmd!
    autocmd BufReadPost * call setpos(".", getpos("'\""))
augroup END

 " enable cursorline in the currently active window
augroup cursorline
    autocmd!
    autocmd VimEnter,WinEnter,BufWinEnter * setlocal cursorline
    autocmd WinLeave * setlocal nocursorline
augroup END

" File information
com! RelativePath let @+=expand("%")
com! GithubPath let @+=expand("%")
com! AbsolutePath let @+=expand("%:p")
com! FileName let @+=expand("%:t")
com! PathName let @+=expand("%:p:h")

" Json things
com! FormatJSON :%!jq '.'
com! MinifyJSON :%!jq -c

" Command to reload vim
com! RVimRc :source ~/.vimrc

" start vim at insert mode when commiting
au FileType gitcommit 1 | startinsert

" Rust
autocmd BufNewFile,BufRead *.rs set filetype=rust

" C programming
com! CRun :!./%<
com! CCompile :!gcc % -lm -o %<
com! CCompileRun :!gcc % -lm -o %< && ./%<

autocmd FileType c map <silent> <F2> :w <CR> :CCompileRun <CR>
autocmd FileType rust map <silent> <F2> :w <CR> :RustRun <CR>

" git
com! Gu :Git push
com! Gp :Git publish

" Solve problem when starting startify on neovim (https://www.reddit.com/r/neovim/comments/5far5t/open_most_recently_used_file_on_startup/)
" autocmd VimEnter * nested
"       \  if argc() == 0
"       \|   let last = filter(filter(copy(v:oldfiles), 'match(v:val, getcwd()) == 0'), 'filereadable(v:val)')
"       \|   if !empty(last)
"       \|     execute 'edit' fnameescape(last[0])
"       \|   endif
"       \| endif
