" Function to load all files inside a folder
function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/.vim/' . a:directory . '/*'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
      execute 'source' config_file
    endif
  endfor
endfunction

function! SourceExists(file)
  if filereadable(a:file)
    exe 'source '.a:file
  endif
endfunction

for plugin in keys(g:plugs)
  call SourceExists(plugin.'/config.vim')
  call SourceExists(plugin.'/config.local.vim')
endfor

" Install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Install plug-ins
call plug#begin('~/.vim/plugged')
call s:SourceConfigFilesIn('plugins')
call plug#end()

" Load configs
call s:SourceConfigFilesIn('configs')
