zstyle ':zim:zmodule' use 'degit'

ZIM_HOME=~/.zim

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
      https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi

source ${ZIM_HOME}/init.zsh

##### ALIAS #####

# General
alias v="vim ."
alias sv="sudo vim"
alias nv="nvim"
alias :q="exit"
alias q="exit"

# Ruby/Rails
alias s="bundle exec rails server"
alias c="bundle exec rails console"
alias br="bundle exec rspec"
alias r="bin/rspec"

# Elixir/Phoenix
alias mi="iex -S mix"
alias mps="mix phx.server"
alias mc="mix do deps.compile, compile"
alias mcc="rm -rf _build && mix do clean, deps.compile, compile"
alias mips="iex -S mix phx.server"

##### SCRIPTS #####
export PATH=$PATH:${HOME}/.local/bin/:$HOME/bin:$HOME/.scripts:$HOME/.docker_scripts:$HOME/.hidden_scripts

##### history on erlang #####
export ERL_AFLAGS="\
  +S 1:1 \
  -kernel shell_history enabled \
  -kernel shell_history_file_bytes 1048576 \
  -kernel shell_history_path '\"$HOME/.erlang-history\"' \
  -kernel shell_history_drop '[\"q().\",\"init:stop().\",\"halt().\"]'"

# fix time on zsh
export TIMEFMT=$'\nreal \t%E\nuser \t%U\nsys \t%S\ncpu \t%P\n'

# import colorscheme from 'wal'
(cat ~/.cache/wal/sequences &)
